name: Build and Test

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  install-dependencies:
    name: Install dependencies
    runs-on: macos-11
    strategy:
      matrix:
        node: [14]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: 'yarn'
          cache-dependency-path: |
            ./yarn.lock
            ./example/yarn.lock
      - name: Install Dependencies
        run: |
          yarn install --cwd example --frozen-lockfile
          yarn install --frozen-lockfile
  
  lint:
    name: Lint files
    runs-on: macos-11
    needs: install-dependencies
    steps:
      run: |
        cd react-native-time-input/react-native-time-input
        yarn lint

  typescript:
    name: Typecheck files
    runs-on: macos-11
    needs: install-dependencies
    steps:
      run: |
        cd react-native-time-input/react-native-time-input
        yarn typescript

  unit-tests:
    name: Run unit tests
    runs-on: macos-11
    needs: install-dependencies
    steps:
      run: |
        cd react-native-time-input/react-native-time-input
        yarn test --coverage

  build-package:
    name: Build package
    runs-on: macos-11
    needs: install-dependencies
    steps:
      run: |
        cd react-native-time-input/react-native-time-input
        yarn prepare
